name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # Veya kendi ana dalınıza göre ayarlayın

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
        
    - name: Build with Maven
      run: mvn clean install
      
    - name: Copy artifacts to server
      run: |
        ./gradlew build
        rsync -avz -e "sshpass -p ${{ secrets.SERVER_SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no" build/* root@172.232.209.75:/home/gztlr/gztlr.jar
      env:
        SERVER_SSH_PASSWORD: ${{ secrets.SERVER_SSH_PASSWORD }}
